import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { copyFile, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd().endsWith('frontend') ? path.resolve(process.cwd(), '..') : process.cwd();
const frontend = path.join(root, 'frontend');
const packageJson = JSON.parse(await readFile(path.join(frontend, 'package.json'), 'utf8'));
const gradle = await readFile(path.join(frontend, 'android', 'app', 'build.gradle'), 'utf8');
const versionName = gradle.match(/versionName\s+"([^"]+)"/)?.[1];
const versionCode = Number(gradle.match(/versionCode\s+(\d+)/)?.[1]);
if (packageJson.version !== versionName || versionName !== '1.3.2' || versionCode !== 132) throw new Error('Las versiones no coinciden. Ejecuta npm run version:check.');
const apk = path.join(frontend, 'android', 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk');
const bytes = await readFile(apk).catch(() => { throw new Error('No existe APK release. Configura la firma externa y ejecuta assembleRelease.'); });
const signingFile = path.join(frontend, 'android', 'keystore.properties');
await stat(signingFile).catch(() => { throw new Error('Falta keystore.properties externo; se rechaza preparar una release sin firma configurada.'); });
const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
if (!sdk) throw new Error('Define ANDROID_HOME para verificar la firma con apksigner.');
const buildTools = path.join(sdk, 'build-tools');
const versions = (await import('node:fs/promises')).readdir(buildTools, { withFileTypes: true });
const latest = (await versions).filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort((a, b) => b.localeCompare(a, undefined, { numeric: true }))[0];
const apksigner = path.join(buildTools, latest, process.platform === 'win32' ? 'apksigner.bat' : 'apksigner');
const verification = execFileSync(apksigner, ['verify', '--verbose', '--print-certs', apk], { encoding: 'utf8', shell: process.platform === 'win32' });
if (!/Verified using v\d scheme[^:]*:\s*true/i.test(verification) || /Android Debug/i.test(verification)) throw new Error('La APK no tiene una firma release valida o usa certificado Android Debug.');
const hash = createHash('sha256').update(bytes).digest('hex');
const output = path.join(root, 'release-output');
await mkdir(output, { recursive: true });
const apkName = `control-financiero-ruben-v${versionName}.apk`;
await copyFile(apk, path.join(output, apkName));
const manifest = { versionName, versionCode, minimumSupportedVersionCode: 120, publishedAt: new Date().toISOString(), apkUrl: `https://github.com/rubbeen/control-financiero-ruben/releases/download/v${versionName}/${apkName}`, sha256: hash, fileSizeBytes: bytes.length, mandatory: false, releasePageUrl: `https://github.com/rubbeen/control-financiero-ruben/releases/tag/v${versionName}`, releaseNotes: ['Recupera automaticamente los datos del esquema anterior sin borrarlos.', 'Funciona mientras Firestore termina de construir los indices.', 'Mantiene cuentas, movimientos y saldos por UID.'] };
await writeFile(path.join(output, 'update-manifest.json'), JSON.stringify(manifest, null, 2));
await writeFile(path.join(output, 'release-checklist.md'), `# Release ${versionName}\n\n- [ ] Verificar firma con apksigner.\n- [ ] Confirmar SHA-256: \`${hash}\`.\n- [ ] Probar instalacion y actualizacion manual.\n- [ ] Adjuntar APK a GitHub Release.\n- [ ] Publicar update-manifest.json solo despues del APK.\n- [ ] Conservar keystore fuera del repositorio.\n`);
console.log(`Release local preparada en ${output}. No se publico ningun archivo.`);
